name: ❓ Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide details so we can assist you effectively.
        
        **Note**: For general discussions or broader topics, consider using [GitHub Discussions](https://github.com/ivviiviivvi/classroom-rpg-aetheria/discussions) instead.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - Installation and Setup
        - Usage and Features
        - Development and Contributing
        - Video Production
        - Configuration
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background information
      placeholder: What are you trying to accomplish? What have you tried so far?
    validations:
      required: false

  - type: textarea
    id: attempts
    attributes:
      label: What Have You Tried?
      description: Have you already attempted to find the answer?
      placeholder: |
        - Searched documentation
        - Checked existing issues
        - Tried specific approaches
    validations:
      required: false

  - type: input
    id: documentation
    attributes:
      label: Related Documentation
      description: Have you checked any documentation? If so, which sections?
      placeholder: e.g., README.md, CONTRIBUTING.md, docs/getting-started.md

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might help us answer your question
      placeholder: Environment details, screenshots, code snippets, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have checked the documentation
          required: true
        - label: This is a specific question (not a general discussion topic)
          required: true
